<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RootNamespace>T_PACE</RootNamespace>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.79" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
	</ItemGroup>

	<!-- NOVO: Forçando a logo a ser empacotada no aplicativo -->
	<ItemGroup>
		<Resource Include="logo.png" />
	</ItemGroup>

</Project>